# Generated by Django 5.1.1 on 2024-10-09 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_posts_options_posts_tags'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='posts',
            managers=[
            ],
        ),
    ]
