version: '3.8'

services:
    proxy:
        build: ./server
        container_name: proxy_server_container
        ports:
            - "3000:80"
        volumes:
            - ./server/nginx.conf:/etc/nginx/nginx.conf
            - ./server/static/:/static/
        networks:
            - bloga
        depends_on:
            - blog
            - media_store
            - session_store
            - database
            - connection_pool
    
    blog:
        build: ./Bloga
        deploy:
            replicas: 6
        volumes:
            - ./Bloga:/app
            - media:/app/media
        depends_on:
            - session_store
            - media_store
            - database
            - connection_pool
        networks:
            - bloga
    
    api:
        build: ./Bloga
        deploy:
            replicas: 4
        volumes:
            - ./Bloga:/app
            - media:/app/media
        depends_on:
            - session_store
            - media_store
            - database
            - connection_pool
        networks:
            - bloga
        environment:
            - PORT=4444
 
    admin:
        build: ./Bloga
        deploy:
            replicas: 2
        volumes:
            - ./Bloga:/app
            - media:/app/media
        depends_on:
            - session_store
            - media_store
            - database
            - connection_pool
        networks:
            - bloga
        environment:
            - PORT=5555

    media_store:
        build: ./uploads
        container_name: media_store_container
        volumes:
            - media:/usr/share/nginx/html/media/
        networks:
            - bloga
        logging:
            driver: "none"

    session_store:
        build: './session store'
        container_name: session_store
        networks:
            - bloga
        depends_on:
            - database
        logging:
            driver: "none"

    connection_pool:
        build: './connection pool'
        container_name: connection_pool
        secrets:
            - pgbouncer_userlist
        volumes:
            - ./connection pool/pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini
        environment:
            DB_HOST: database
        networks:
            - bloga
        depends_on:
            - database
        logging:
            driver: "none"

    database:
        build: './database'
        container_name: postgres
        environment:
            POSTGRES_DB: Bloga
            POSTGRES_USER: jehoshaphat
            POSTGRES_PASSWORD: Pentatonic5464@

        volumes:
            - postgres_data:/var/lib/postgresql/data
            - ./database/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
            - ./database/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
        networks:
            - bloga
        logging:
            driver: "none"

secrets:
    pgbouncer_userlist:
        file: ./connection pool/pg_bouncer_secret.txt

volumes:
    media:
    postgres_data:

networks:
    bloga:
        ipam:
            driver: default
            config:
                - subnet: "192.168.93.0/24"

