version: "3.8"

services:
    proxy:
        build: ./server
        container_name: proxy_server_container
        ports:
            - "3000:80"
        volumes:
            - ./server/nginx.conf:/etc/nginx/nginx.conf
            - ./server/static/:/static/
        networks:
            bloga:
                ipv4_address: 192.168.93.2
        depends_on:
            - blog1
            - media_store
            - session_store
    blog1:
        build: ./Bloga
        container_name: blog1_server_container
        volumes:
            - ./Bloga:/app
            - media:/app/media
        depends_on:
            - session_store
            - media_store
        networks:
            bloga:
                ipv4_address: 192.168.93.3

    media_store:
        build: ./uploads
        container_name: media_store_container
        volumes:
            - media:/usr/share/nginx/html/media/
        networks:
            bloga:
                ipv4_address: 192.168.93.4

    session_store:
        build: './session store'
        container_name: session_store
        networks:
            bloga:
                ipv4_address: 192.168.93.5

volumes:
    media:

networks:
    bloga:
        ipam:
            driver: default
            config:
                - subnet: "192.168.93.1/24"

