FROM python:3.12-slim

# Install required dependencies for mysqlclient or other MySQL-based packages
RUN apt-get update && apt-get install -y
RUN apt-get install libmariadb-dev -y
RUN apt-get install build-essential -y
RUN apt-get install pkg-config -y
RUN rm -rf /var/lib/apt/lists/*
    
RUN ln -s /bin/python3 /bin/python    

RUN pip install --upgrade pip

# Update the package list and install libpq-dev
RUN apt-get update && apt-get install -y libpq-dev postgresql-client



WORKDIR /app

# Copy requirements
COPY ./requirements.txt /app/requirements.txt

# Install dependencies
RUN pip --no-cache-dir install -U wheel

RUN pip --no-cache-dir install -r requirements.txt
RUN pip --no-cache-dir install psycopg2-binary

# Launch the app
COPY ./entrypoint.sh /
ENTRYPOINT [ "sh", "/entrypoint.sh" ]